baseurl = 'https://w1ndsor.github.io'
languageCode = "en-us"
title = "Windsor"
theme = "hugo-theme-stack"

[[menu.main]]
  identifier = "ankit"
  name = "Ankit"
  url = "https://github.com/ankitkat042"
  [menu.main.params]
    icon = "user"
    newtab = true

[[menu.main]]
  identifier = "chaitanya"
  name = "Chaitanya"
  url = "https://github.com/Chaitanya21033"
  [menu.main.params]
    icon = "user"
    newtab = true

[[menu.main]]
  identifier = "lakshay"
  name = "Lakshay"
  url = "https://github.com/hyouteki"
  [menu.main.params]
    icon = "user"
    newtab = true

[[menu.main]]
  identifier = "sameer"
  name = "Sameer"
  url = "https://github.com/guptasameer112"
  [menu.main.params]
    icon = "user"
    newtab = true

[[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/W1NDSOR"
  [menu.social.params]
    icon = "brand-github"

[params]
  # Pages placed under these sections will be shown on homepage and archive page.
  mainSections = ["projects"]
  # Output page's full content in RSS.
  favicon = "/avatar.jpg"

  [params.footer]
  since = 2023
  # customText = "Made with love by Windsor"

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = ""
  subtitle = "P.S. Not affiliated with 'House of Windsor'"

  [params.sidebar.avatar]
  enabled = false
  local = true
  src = "/avatar.jpg"

  [params.article]
  math = false
  readingTime = true

  [params.article.license]
  enabled = true
  default = "Licensed under MIT"

  ## Widgets
  [[params.widgets.homepage]]
  type = "search"

  [[params.widgets.homepage]]
  type = "archives"
  params.limit = 5

  [[params.widgets.homepage]]
  type = "categories"
  params.limit = 10

  [[params.widgets.homepage]]
  type = "tag-cloud"
  params.limit = 10

  [[params.widgets.page]]
  type = "toc"

  [params.defaultImage.opengraph]
  enabled = false
  local = false
  src = ""

  [params.colorScheme]
  toggle = true
  default = "auto"

  [params.imageProcessing.cover]
  enabled = true

  [params.imageProcessing.content]
  enabled = true
